export const ListaLojas = [
    {
        grupo: "roland",
        numLoja: "loja1",
        nomeLoja: "Studio WO",
        categoria: "Beleza",
        imageUrl: "/wo.png",
        endereco: "Tv. Tempestade, 22",
        mapa: "gal, salão studio wo",
        telefone: "999999999",
        whatsapp: "5511986197028",
        linkInstagram: "https://www.instagram.com/studiowo.salao",
        site: "",
        descricao: "A missão, desde a fundação foi atender bem, e promover a satisfação dos clientes. Durante muitos anos presente na avenida temos histórias pra contar. Cortes, escova, alisamento, cuidados com as mãos e pés. Tudo com qualidade e responsabilidade.",
        produtos: ["Corte", "Escova", "Alisamento"],
    },
    {
        grupo: "roland",
        numLoja: "loja2",
        nomeLoja: "Avícola Alvorada",
        categoria: "Avicula",
        imageUrl: "/alvoradaGemRC.png",
        endereco: "Av. Roland Garros, 1039",
        mapa: "Avícola Alvorada",
        linkInstagram: '',
        descricao: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis aut obcaecati magnam aliquam ea sequi impedit at, asperiores delectus illum et a tempore officia deleniti commodi veniam architecto. Optio, veniam?"
    },
    {
        grupo: "chaves",
        numLoja: "loja3",
        nomeLoja: "Okinalar Nikei",
        categoria: "Ferragens",
        imageUrl: "/casabella1000.png",
        endereco: "Av. Edu Chaves, 645",
        mapa: "Av. Edu Chaves, 653",
        linkInstagram: "",
        descricao: "O Center Okinalar surgiu em 1990 com a reunião de 25 lojistas, que passaram a fazer compras em conjunto para obter melhores negociações junto aos fornecedores e unir empresários do setor para troca de experiências e informações."
    },
    {
        grupo: "chaves",
        numLoja: "loja4",
        nomeLoja: "OPTICA AMETISTA",
        categoria: "Oticas",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Edu Chaves, 733",
        mapa: "OPTICA AMETISTA",
        linkInstagram: "",
        descricao: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis aut obcaecati magnam aliquam ea sequi impedit at, asperiores delectus illum et a tempore officia deleniti commodi veniam architecto. Optio, veniam?"
    },
    {
        grupo: "roland",
        numLoja: "loja5",
        nomeLoja: "Swift",
        categoria: "Açougue",
        imageUrl: "/swiftGemRD.png",
        endereco: "Av. Roland Garros, 1300",
        mapa: "Swift - Roland Garros",
        linkInstagram: "",
        descricao: "lorem ipsum lorem lorem Lorem ipsum, dolor sit amet consectetur adipisicing elit. Possimus cumque dolores in tempora harum rerum ea! Reiciendis eveniet corporis officia aliquam fugiat. Corporis facilis at saepe ab eveniet, doloremque eum.",
        produtos: [],
    },
    {
        grupo: "roland",
        numLoja: "loja6",
        nomeLoja: "Bergamini",
        categoria: "Mercado",
        imageUrl: "/bergaminiGemRD.png",
        endereco: "Av. Roland Garros, 1765",
        mapa: "Supermercados Bergamini",
        linkInstagram: "",
        descricao: "lorem ipsum lorem lorem Lorem ipsum, dolor sit amet consectetur adipisicing elit. Possimus cumque dolores in tempora harum rerum ea! Reiciendis eveniet corporis officia aliquam fugiat. Corporis facilis at saepe ab eveniet, doloremque eum.",
        produtos: [],
    },
    {
        grupo: "roland",
        numLoja: "loja7",
        nomeLoja: "Tintas HB",
        categoria: "Construcao",
        imageUrl: "/hbtintasGemRD.png",
        endereco: "Av. Roland Garros, 1400",
        mapa: "HB Tintas Zona Norte",
        linkInstagram: "",
        descricao: "A HB Tintas é uma empresa familiar, fundada em 2008. Nossos valores foram construídos a partir do que acreditamos e principalmente na nossa vontade de deixar o mundo mais alegre, colorido, inclusivo e sobretudo com oportunidades para todos. ",
        produtos: [],
    },
    {
        grupo: "roland",
        numLoja: "loja8",
        nomeLoja: "Farmais",
        categoria: "Farmacia",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Roland Garros, 1054",
        mapa: "Drogaria Farmais Roland garros",
        linkInstagram: "",
        descricao: "A FARMAIS foi a pioneira no País no sistema de franquia no segmento de farmácias, fundada em 1994, quando criou um novo conceito de conversão de farmácias independentes, para unidades de rede forte e sustentável.Nosso comprometimento é a seriedade, valorização dos nossos franqueados e consumidores, confirmada pelo reconhecimento dos clientes, que serve de estímulo para continuar crescendo sempre com os mais elevados padrões éticos, profissionais e de qualidade.",
        produtos: [],
    },
    {
    grupo: "roland",
    numLoja: "loja9",
    nomeLoja: "De Bellis",
    categoria: "Otica",
    imageUrl: "/padrao.jpg",
    endereco: "Av. Roland Garros, 1524",
    mapa: "Óticas De bellis - Jd Brasil - SP",
    linkInstagram: "",
    descricao: "Iniciamos no ramo da Ótica em 1994.  Nos aperfeiçoamos  através do Curso Técnico em Ótica no Senac em 1995. A  primeira lição aprendida foi levar a sério a saúde visual, e este conceito levamos muito além da Ótica, estendemos para nossas vidas.",
    produtos: [],
    },
    {
        grupo: "roland",
        numLoja: "loja10",
        nomeLoja: "RC Ótica",
        categoria: "Otica",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Roland Garros, 1470",
        mapa: "Fábrica de óculos RC Ótica",
        linkInstagram: "",
        descricao: "RC Ótica",
        produtos: [],
    },
    {
        grupo: "roland",
        numLoja: "loja11",
        nomeLoja: "Kamp Esquadrias",
        categoria: "Construcao",
        imageUrl: "/casabella1000.png",
        endereco: "Av. Roland Garros, 922",
        mapa: "Kamp Esquadrias Portas Madeira e Aluminio",
        linkInstagram: "",
        descricao: "A Kamp esquadrias esta no mercado há mais de 20 anos, sempre visando a satisfação dos seus clientes e priorizando a qualidade dos seus produtos.",
        produtos: [],
    },
    {
        grupo: "roland",
        numLoja: "loja12",
        nomeLoja: "G2 ATACADO DE BEBIDAS",
        categoria: "Bebidas",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Roland Garros, 923",
        mapa: "G2 ATACADO DE BEBIDAS",
        linkInstagram: "",
        descricao: "Para quem busca variedade e qualidade em bebidas a G2 Atacadista é referência no mercado atendendo estabelecimentos e eventos eles garantem satisfação em cada entrega um brinde a expertise da G2 Atacadista. Há mais de 30 anos no mercado.",
        produtos: [],
    },
    {
        grupo: "roland",
        numLoja: "loja13",
        nomeLoja: "Peppy Automóveis",
        categoria: "Automoveis",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Roland Garros, 849",
        mapa: "Peppy Automóveis",
        linkInstagram: "",
        descricao: "Somos apaixonados por carros, não apenas pelo que ele é, mas pelo que ele representa. Um carro é um sonho, e atendemos nossos clientes tendo isso como foco. Aqui na Peppy Automóveis procuramos realizar o seu sonho e fazer com que você, nosso cliente, tenha uma experiência única na hora de comprar o seu carro",
        produtos: [],
    },
    {
        grupo: "chaves",
        numLoja: "loja14",
        nomeLoja: "Rainha do Parque",
        categoria: "Padaria",
        imageUrl: "/rainha.jpg",
        endereco: "Av. Edu Chaves, 584",
        mapa: "Rainha do Parque",
        telefone: "",
        whatsapp: "",
        linkInstagram: "https://www.instagram.com/padariarainhadoparque/",
        site: "",
        descricao: "Padaria Rainha do Parque - um ótimo lugar para você e sua família saborear delícias para seu café da manhã, café da tarde, almoço, lanches, doces e sopas.",
        produtos: [],
    },
    {
        grupo: "chaves",
        numLoja: "loja15",
        nomeLoja: "Doce Pimenta",
        categoria: "Moda",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Edu Chaves, ",
        mapa: "Doce Pimenta Moda Feminina",
        telefone: "",
        whatsapp: "",
        linkInstagram: "",
        site: "",
        descricao: "Criando looks com muito carinho em função de satisfazer o seu bem estar e sua melhor versão. Estilo, qualidade e atendimento. Doce Pimenta Moda Feminina.",
        produtos: [],
    },
    {
        grupo: "chaves",
        numLoja: "loja16",
        nomeLoja: "Tele Cell",
        categoria: "Celulares",
        imageUrl: "/telecell.jpg",
        endereco: "Av. Edu Chaves, 622",
        mapa: "Tele Cell acessórios & assistência técnica",
        telefone: "",
        whatsapp: "",
        linkInstagram: "",
        site: "",
        descricao: "Criando looks com muito carinho em função de satisfazer o seu bem estar e sua melhor versão. Estilo, qualidade e atendimento. Doce Pimenta Moda Feminina.",
        produtos: [],
    },
    {
        grupo: "chaves",
        numLoja: "loja17",
        nomeLoja: "Pet Stop",
        categoria: "Pet",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Edu Chaves, 669A",
        mapa: "Pet Stop",
        telefone: "",
        whatsapp: "",
        linkInstagram: "",
        site: "",
        descricao: "Av. Edu Chaves, 669A - Parque Edu Chaves, São Paulo - SP, 02229-000",
        produtos: [],
    },
    {
        grupo: "japao",
        numLoja: "loja18",
        nomeLoja: "Oggi Sorvetes",
        categoria: "Alimentacao",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Jardim Japão, 1272",
        mapa: "Oggi Sorvetes Jardim Japão",
        telefone: "",
        whatsapp: "5511989981908",
        linkInstagram: "",
        site: "",
        descricao: "Democratizar o acesso a um sorvete de qualidade para todos os brasileiros e ajudar pequenos empreendedores a abrirem seu próprio negócio",
        produtos: [],
    },
    {
        grupo: "japao",
        numLoja: "loja19",
        nomeLoja: "Mega Acessorios",
        categoria: "Celulares",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Jardim Japão, ",
        mapa: "MEGA ACESSORIOS",
        telefone: "",
        whatsapp: "5511948996243",
        linkInstagram: "",
        site: "",
        descricao: "Loja de acessórios para celular",
        produtos: [],
    },
    {
        grupo: "japao",
        numLoja: "loja20",
        nomeLoja: "Padaria Jardim Brasil",
        categoria: "Alimentacao",
        imageUrl: "/padaria-jb.png",
        endereco: "Av. Jardim Japão, 1298",
        mapa: "Padaria Jardim Brasil",
        telefone: "(11) 2201-9434",
        whatsapp: "",
        linkInstagram: "",
        site: "",
        descricao: "Jardim Brasil Pães e Doces foi a primeira padaria no bairro. A missão, desde a fundação em 1956, é promover a satisfação dos clientes internos e externos com alegria, qualidade e responsabilidade. Ao longo de mais de meio século de tradição, a padaria passou por inúmeras transformações, ampliando os setores de produção e agregando novos mix de produtos, buscando sempre o destaque pela qualidade e variedade oferecida.",
        produtos: [],
    },
    {
        grupo: "chaves",
        numLoja: "loja21",
        nomeLoja: "Oggi Sorvetes",
        categoria: "Alimentacao",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Edu Chaves, 808",
        mapa: "Oggi Sorvetes Edu Chaves",
        telefone: "",
        whatsapp: "5511992468841",
        linkInstagram: "",
        site: "",
        descricao: "Democratizar o acesso a um sorvete de qualidade para todos os brasileiros e ajudar pequenos empreendedores a abrirem seu próprio negócio",
        produtos: [],
    },
    {
        grupo: "chaves",
        numLoja: "loja22",
        nomeLoja: "Farmais",
        categoria: "Farmacia",
        imageUrl: "/padrao.jpg",
        endereco: "Av. Edu Chaves, 809",
        mapa: "Drogaria Farmais Edu Chaves",
        linkInstagram: "",
        descricao: "A FARMAIS foi a pioneira no País no sistema de franquia no segmento de farmácias, fundada em 1994, quando criou um novo conceito de conversão de farmácias independentes, para unidades de rede forte e sustentável.Nosso comprometimento é a seriedade, valorização dos nossos franqueados e consumidores, confirmada pelo reconhecimento dos clientes, que serve de estímulo para continuar crescendo sempre com os mais elevados padrões éticos, profissionais e de qualidade.",
        produtos: [],
    },
    
    
]
